// Mocks generated by Mockito 5.4.6 from annotations
// in tyarekyara/test/feature/statistics/badge_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tyarekyara/feature/statistics/models/badge.dart' as _i4;
import 'package:tyarekyara/feature/statistics/models/earned_badge.dart' as _i5;
import 'package:tyarekyara/feature/statistics/repositories/badge_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BadgeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeRepository extends _i1.Mock implements _i2.BadgeRepository {
  MockBadgeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Badge>> fetchCatalog() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCatalog, []),
            returnValue: _i3.Future<List<_i4.Badge>>.value(<_i4.Badge>[]),
          )
          as _i3.Future<List<_i4.Badge>>);

  @override
  _i3.Future<List<_i4.Badge>> fetchEarnedBadges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEarnedBadges, [userId]),
            returnValue: _i3.Future<List<_i4.Badge>>.value(<_i4.Badge>[]),
          )
          as _i3.Future<List<_i4.Badge>>);

  @override
  _i3.Future<void> saveEarnedBadge(
    String? userId,
    _i5.EarnedBadge? earnedBadge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEarnedBadge, [userId, earnedBadge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
