// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmqGoLBvLi6UpjpX7EKfh-87GOUHvWMHw',
    appId: '1:662430133513:web:1bbcddd9a898cfcbe577d8',
    messagingSenderId: '662430133513',
    projectId: 'tyarekyara-85659',
    authDomain: 'tyarekyara-85659.firebaseapp.com',
    storageBucket: 'tyarekyara-85659.firebasestorage.app',
    measurementId: 'G-JFZ3ERCZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBfLfj3HiuEicN6eDD0ydoWgQPpavrwps',
    appId: '1:662430133513:android:c28d96e507d25330e577d8',
    messagingSenderId: '662430133513',
    projectId: 'tyarekyara-85659',
    storageBucket: 'tyarekyara-85659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PFGLtQR0P6hgCU9OjJHgueTb82j0pwk',
    appId: '1:662430133513:ios:675147952b3a7d36e577d8',
    messagingSenderId: '662430133513',
    projectId: 'tyarekyara-85659',
    storageBucket: 'tyarekyara-85659.firebasestorage.app',
    iosBundleId: 'com.example.tyarekyara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PFGLtQR0P6hgCU9OjJHgueTb82j0pwk',
    appId: '1:662430133513:ios:675147952b3a7d36e577d8',
    messagingSenderId: '662430133513',
    projectId: 'tyarekyara-85659',
    storageBucket: 'tyarekyara-85659.firebasestorage.app',
    iosBundleId: 'com.example.tyarekyara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmqGoLBvLi6UpjpX7EKfh-87GOUHvWMHw',
    appId: '1:662430133513:web:adf018024f8a195ee577d8',
    messagingSenderId: '662430133513',
    projectId: 'tyarekyara-85659',
    authDomain: 'tyarekyara-85659.firebaseapp.com',
    storageBucket: 'tyarekyara-85659.firebasestorage.app',
    measurementId: 'G-LKYT1EQN7F',
  );
}
